name: Android Build and Release

on:
  push:
    branches:
      - master

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk

  tag:
    name: Bump version and create new Tag
    needs: apk
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag_version: ${{ steps.version_bump.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: version_bump
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          PRERELEASE: false

  release:
    name: Release APK
    needs: tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Get Commits since last Release
        id: changes
        uses: simbo/changes-since-last-release-action@v1
        with:
          line-prefix: "* "
          include-hashes: false
      - name: Create a new release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          makeLatest: true
          generateReleaseNotes: false
          tag: ${{ needs.tag.outputs.tag_version }}
          body: |
            Changes since ${{ steps.changes.outputs.last-tag }}:
            ${{ steps.changes.outputs.log }}
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/app-debug.apk
          asset_name: Spelldex.apk
          asset_content_type: application/zip